sections = {
    section_1: {
        section_title: 'tokyo',
        id: 1,
        accommodationItems: {
            item1: {
                id: 1,
                title: 'test 1',
                link: 'https://github.com/UofTTeam2/TravIs/tree/dev',
                image: 'https://i.pinimg.com/736x/b2/32/63/b23263218ede5b69d4e1a7d01660410c.jpg',
                startDate: '2023-10-17',
                startTime: '4:00 PM',
                endDate: '2024-01-19',
                endTime: '11:00 AM',
                expense: '$400',
                notes: 'AS a frequent traveler, WHEN I travel in VR, I WANT to see Ehsan there as well',
            },
            item2: {
                id: 2,
                title: 'test 2',
                link: 'https://drinkarizona.com/collections/hats/products/big-blossom-bucket-hat',
                image: 'https://cultureofgaming.com/wp-content/uploads/2023/02/the-way-of-the-kings-stormlight-archives.png',
                startDate: '2023-10-17',
                startTime: '4:00 PM',
                endDate: '2024-01-19',
                endTime: '11:00 AM',
                expense: '$400',
                notes: 'AS a frequent traveler, WHEN I travel in VR, I WANT to see Ehsan there as well',
            }
        },
        foodItems: {
            item1: {
                id: 3,
                title: 'peach tea',
                link: 'https://minimalistbaker.com/perfect-peach-iced-tea/',
                image: 'https://minimalistbaker.com/wp-content/uploads/2014/06/Perfect-sweet-Peached-Iced-Tea-Perfect-for-summer-and-pool-days..jpg',
                startDate: '2023-10-17',
                startTime: '4:00 PM',
                endDate: '2024-01-19',
                endTime: '11:00 AM',
                expense: '$400',
                notes: 'AS a frequent traveler, WHEN I travel in VR, I WANT to see Ehsan there as well',
            },
            item2: {
                id: 4,
                title: 'the way of kings',
                link: 'https://www.michaelwhelan.com/shop/way-of-kings/',
                image: 'https://i.redd.it/pty7jq8xvsh71.jpg',
                startDate: '2023-10-17',
                startTime: '4:00 PM',
                endDate: '2024-01-19',
                endTime: '11:00 AM',
                expense: '$5000',
                notes: 'AS a frequent traveler, WHEN I travel in VR, I WANT to see Ehsan there as well',
            },
            item3: {
                id: 5,
                title: '',
                link: '',
                image: '',
                startDate: '2023-10-17',
                startTime: '',
                endDate: '2024-01-19',
                endTime: '',
                expense: '',
                notes: '',
            }
        },
        transportItems: {
            item1: {
                id: 6,
                title: 'the way of kings',
                link: '',
                image: 'https://i.redd.it/pty7jq8xvsh71.jpg',
                startDate: '2023-10-17',
                startTime: '',
                endDate: '2024-01-19',
                endTime: '',
                expense: '',
                notes: 'AS a frequent traveler, WHEN I travel in VR, I WANT to see Ehsan there as well',
            }},
        activityItems: {},
        miscItems: {
            item1: {
                id: 7,
                title: '',
                link: 'https://www.michaelwhelan.com/shop/way-of-kings/',
                image: '',
                startDate: '2023-10-17',
                startTime: '4:00 PM',
                endDate: '',
                endTime: '11:00 AM',
                expense: '$5000',
                notes: '',
            }
        }
    },
    section_2: {
        id: 3,
        section_title: 'osaka',
        accommodationItems: {
            item1: {
                id: 8,
                title: 'test 1',
                link: 'https://github.com/UofTTeam2/TravIs/tree/dev',
                image: 'https://i.pinimg.com/736x/b2/32/63/b23263218ede5b69d4e1a7d01660410c.jpg',
                startDate: '2023-10-17',
                startTime: '4:00 PM',
                endDate: '2024-01-19',
                endTime: '11:00 AM',
                expense: '$400',
                notes: 'AS a frequent traveler, WHEN I travel in VR, I WANT to see Ehsan there as well',
            },
            item2: {
                id: 9,
                title: 'test 2',
                link: 'https://drinkarizona.com/collections/hats/products/big-blossom-bucket-hat',
                image: 'https://cultureofgaming.com/wp-content/uploads/2023/02/the-way-of-the-kings-stormlight-archives.png',
                startDate: '2023-10-17',
                startTime: '4:00 PM',
                endDate: '2024-01-19',
                endTime: '11:00 AM',
                expense: '$400',
                notes: 'AS a frequent traveler, WHEN I travel in VR, I WANT to see Ehsan there as well',
            }
        },
        foodItems: {
            item1: {
                id: 10,
                title: 'peach tea',
                link: 'https://minimalistbaker.com/perfect-peach-iced-tea/',
                image: 'https://minimalistbaker.com/wp-content/uploads/2014/06/Perfect-sweet-Peached-Iced-Tea-Perfect-for-summer-and-pool-days..jpg',
                startDate: '2023-10-17',
                startTime: '4:00 PM',
                endDate: '2024-01-19',
                endTime: '11:00 AM',
                expense: '$400',
                notes: 'AS a frequent traveler, WHEN I travel in VR, I WANT to see Ehsan there as well',
            },
            item2: {
                id: 11,
                title: 'the way of kings',
                link: 'https://www.michaelwhelan.com/shop/way-of-kings/',
                image: 'https://i.redd.it/pty7jq8xvsh71.jpg',
                startDate: '2023-10-17',
                startTime: '4:00 PM',
                endDate: '2024-01-19',
                endTime: '11:00 AM',
                expense: '$5000',
                notes: 'AS a frequent traveler, WHEN I travel in VR, I WANT to see Ehsan there as well',
            },
            item3: {
                id: 14,
                title: '',
                link: '',
                image: '',
                startDate: '2023-10-17',
                startTime: '',
                endDate: '2024-01-19',
                endTime: '',
                expense: '',
                notes: '',
            }
        },
        transportItems: {
            item1: {
                id: 29,
                title: 'the way of kings',
                link: '',
                image: 'https://i.redd.it/pty7jq8xvsh71.jpg',
                startDate: '2023-10-17',
                startTime: '',
                endDate: '2024-01-19',
                endTime: '',
                expense: '',
                notes: 'AS a frequent traveler, WHEN I travel in VR, I WANT to see Ehsan there as well',
            }},
        activityItems: {},
        miscItems: {
            item1: {
                id: 45,
                title: '',
                link: 'https://www.michaelwhelan.com/shop/way-of-kings/',
                image: '',
                startDate: '2023-10-17',
                startTime: '4:00 PM',
                endDate: '',
                endTime: '11:00 AM',
                expense: '$5000',
                notes: '',
            }
        }
    }
};

module.exports = sections;